// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Build a boat and reach the treasure at the end of the river.",
      "Tap the build grid to place blocks. Add a seat, then press START to launch.",
      "Use the steering controls to dodge obstacles. Wood floats; heavy blocks need a wide hull."
    ],
    "ru": [
      "Построй лодку и доберись до сокровища в конце реки.",
      "Нажимай на сетку, чтобы ставить блоки. Добавь сиденье и нажми СТАРТ.",
      "Управляй лодкой, обходя препятствия. Дерево плавает, тяжёлым блокам нужен широкий корпус."
    ]
  }
}
